const woocommerceanalytics_checkout_view = {
  cart_page_contains_cart_block: 1,
  cart_page_contains_cart_shortcode: 0,
  checkout_page_contains_checkout_block: 1,
  checkout_page_contains_checkout_shortcode: 0,
  create_account: No,
  device: desktop,
  guest_checkout: Yes,
  lr: null,
  or: null,
  order_value: 1000,
  products: [{ pp: "1000", pq: 1, pi: 14, pn: "Woo Test" }],
  products_count: 1,
  r3d: null,
  store_currency: EUR,
  ui: null,
  url: "https://wca.jurassic.tube",
  woo_version: "8.3.1",
};
