const woocommerceanalytics_product_purchase = {
  additional_blocks: null,
  cart_page_contains_cart_block: 1,
  cart_page_contains_cart_shortcode: 0,
  checkout_page_contains_checkout_block: 1,
  checkout_page_contains_checkout_shortcode: 0,
  coupon_used: 0,
  create_account: N,
  device: desktop,
  express_checkout: null,
  guest_checkout: Y,
  lr: null,
  oi: 100,
  or: null,
  order_value: 10.0,
  payment_option: bacs,
  pc: Uncategorized,
  pi: 14,
  pn: "Woo Test",
  pp: 10,
  pq: 1,
  products_count: 1,
  pt: simple,
  r3d: null,
  store_admin: 0,
  store_currency: EUR,
  template_used: 0,
  ui: null,
  url: "https://wca.jurassic.tube",
  woo_version: "8.3.1",
};
