const woocommerceanalytics_cart_view = {
  additional_blocks_on_cart_page: [
    "core/template-part",
    "core/post-title",
    "core/post-content",
    "woocommerce/page-content-wrapper",
    "core/group",
    "core/template-part",
  ],
  additional_blocks_on_checkout_page: [
    "core/template-part",
    "core/post-title",
    "core/post-content",
    "woocommerce/page-content-wrapper",
    "core/group",
  ],
  cart_page_contains_cart_block: 1,
  cart_page_contains_cart_shortcode: 0,
  checkout_page_contains_checkout_block: 1,
  checkout_page_contains_checkout_shortcode: 0,
  create_account: No,
  device: desktop,
  guest_checkout: Yes,
  lr: null,
  or: null,
  order_value: 1000,
  products: [{ pp: "1000", pq: 1, pi: 14, pn: "Woo Test", pt: "simple" }],
  products_count: 1,
  r3d: null,
  store_currency: EUR,
  ui: null,
  url: "https://wca.jurassic.tube",
  woo_version: "8.3.1",
};
