const woocommerceanalytics_product_checkout = {
  additional_blocks: [
    "core/template-part",
    "core/group",
    "woocommerce/page-content-wrapper",
  ],
  cart_page_contains_cart_block: 0,
  cart_page_contains_cart_shortcode: 1,
  checkout_page_contains_checkout_block: 0,
  checkout_page_contains_checkout_shortcode: 1,
  coupon_used: 0,
  create_account: No,
  device: desktop,
  express_checkout: null,
  guest_checkout: Yes,
  lr: null,
  or: null,
  order_value: 10.0,
  payment_options: ["bacs", "cheque", "cod", "ppcp-gateway"],
  pc: Uncategorized,
  pi: 14,
  pn: "Woo Test",
  pp: 10,
  pq: 1,
  products_count: 1,
  pt: simple,
  r3d: null,
  shipping_option: "local_pickup:3",
  store_admin: 0,
  store_currency: EUR,
  template_used: 1,
  ui: null,
  url: "https://wca.jurassic.tube",
  woo_version: "8.3.1",
};
